version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.7.1
    container_name: es
    ports:
      - "9200:9200"
    networks:
      - backend


  postgres:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: database
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "user=user password=password dbname=database" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 1s


  backend:
    image: app:1
    container_name: app
    build:
      dockerfile: ./Dockerfile
    environment:
      DATABASE_PASSWORD: password
      DATABASE_USER: user
      DATABASE_NAME: database
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_started
    networks:
      - backend

networks:
  backend:
    driver: bridge


